#!/usr/bin/env bash

if
  [[ -s "/home/sparks/.rvm/gems/ruby-2.0.0-p451/environment" ]]
then
  source "/home/sparks/.rvm/gems/ruby-2.0.0-p451/environment"
  exec executable-hooks-uninstaller "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/sparks/.rvm/gems/ruby-2.0.0-p451/environment'" >&2
  exit 1
fi
