# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1398980409);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1398980529);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1398980289);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1398945180);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 15);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 6);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140410211200");
user_pref("browser.slowStartup.averageTime", 3926);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20140410211200");
user_pref("browser.startup.homepage_override.mstone", "28.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":3}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1398951358170");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1398980230557");
user_pref("datareporting.policy.firstRunTime", "1398864958169");
user_pref("datareporting.sessions.current.activeTicks", 6);
user_pref("datareporting.sessions.current.firstPaint", 5396);
user_pref("datareporting.sessions.current.main", 1247);
user_pref("datareporting.sessions.current.sessionRestored", 6391);
user_pref("datareporting.sessions.current.startTime", "1399019236562");
user_pref("datareporting.sessions.current.totalTime", 31);
user_pref("datareporting.sessions.currentIndex", 6);
user_pref("datareporting.sessions.previous.0", "{\"s\":1398864955572,\"a\":92,\"t\":604,\"c\":false,\"m\":1006,\"fp\":6196,\"sr\":8076}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1398883423915,\"a\":4,\"t\":31,\"c\":false,\"m\":1021,\"fp\":6605,\"sr\":6557}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1398944890595,\"a\":15,\"t\":126,\"c\":true,\"m\":1201,\"fp\":4540,\"sr\":4737}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1398945059212,\"a\":54,\"t\":1673,\"c\":true,\"m\":91,\"fp\":1675,\"sr\":1634}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1398979961682,\"a\":3,\"t\":16,\"c\":true,\"m\":871,\"fp\":3832,\"sr\":4305}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1398980168480,\"a\":56,\"t\":383,\"c\":true,\"m\":51,\"fp\":1401,\"sr\":1550}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.bootstrappedAddons", "{\"webapps-team@lists.launchpad.net\":{\"version\":\"3.0.2\",\"type\":\"extension\",\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\"}}");
user_pref("extensions.databaseSchema", 15);
user_pref("extensions.enabledAddons", "%7B2e1445b0-2682-11e1-bfc2-0800200c9a66%7D:2013.09.20.beta,ubufox%40ubuntu.com:2.8,online-accounts%40lists.launchpad.net:0.5,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:28.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20140319.01");
user_pref("extensions.installCache", "[{\"name\":\"app-system-local\",\"addons\":{\"online-accounts@lists.launchpad.net\":{\"descriptor\":\"/usr/lib/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/online-accounts@lists.launchpad.net\",\"mtime\":1397697896000,\"rdfTime\":1390969548000}}},{\"name\":\"app-system-share\",\"addons\":{\"webapps-team@lists.launchpad.net\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\",\"mtime\":1397697896000,\"rdfTime\":1397665356000},\"{2e1445b0-2682-11e1-bfc2-0800200c9a66}\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{2e1445b0-2682-11e1-bfc2-0800200c9a66}\",\"mtime\":1397697896000,\"rdfTime\":1379719396000},\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1397697896000,\"rdfTime\":1381435136000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1397697838000,\"rdfTime\":1397165556000},\"langpack-ru@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-ru@firefox.mozilla.org.xpi\",\"mtime\":1398716259000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1398716133000},\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1398716133000}}}]");
user_pref("extensions.lastAppVersion", "28.0");
user_pref("extensions.lastPlatformVersion", "28.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20140410211200");
user_pref("gecko.mstone", "28.0");
user_pref("idle.lastDailyNotification", 1398865731);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 75477);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1399019237);
user_pref("toolkit.telemetry.previousBuildID", "20140410211200");
user_pref("urlclassifier.download_allow_table", "");
user_pref("urlclassifier.download_block_table", "");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1401456964);
